version: '3.8'

services:
  mysql_db:
    image: mysql:8.0 # Docker sẽ tự động chọn image ARM64v8 nếu có sẵn cho Mac M2
    container_name: shortlink_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "33066:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    # Thêm dòng này để đảm bảo compatibility nếu gặp lỗi xác thực
#    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
