server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'logstream'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'filename'
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container_name'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'container_log_stream'

  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          service: system
          __path__: /var/log/*log

  - job_name: journal
    journal:
      max_age: 12h
      labels:
        service: systemd-journal
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'

  - job_name: services
    static_configs:
      - targets:
          - localhost
        labels:
          job: services
          __path__: /app/services/*/tmp/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            ts: ts
            msg: msg
            trace_id: trace_id
            span_id: span_id
            method: method
            path: path
      - regex:
          expression: '/app/services/(?P<service>[^/]+)/tmp/.*'
          source: filename
      - labels:
          service:
          level:
          trace_id:
          span_id:
          method:
          path:
      - output:
          source: msg
      - timestamp:
          source: ts
          format: RFC3339Nano

  - job_name: temporal
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: 'temporal'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'logstream'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'filename'
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container_name'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'container_log_stream'
      - target_label: 'service'
        replacement: 'temporal'
    pipeline_stages:
      - json:
          expressions:
            level: level
            ts: ts
            msg: msg
            service: service
            component: component
            wf_task_queue_name: wf_task_queue_name
            wf_task_queue_type: wf_task_queue_type
            wf_namespace: wf_namespace
            lifecycle: lifecycle
      - regex:
          expression: 'workflowID="(?P<workflow_id>[^"]+)"'
          source: msg
      - regex:
          expression: 'workflowType="(?P<workflow>[^"]+)"'
          source: msg
      - regex:
          expression: 'taskQueue="(?P<task_queue>[^"]+)"'
          source: msg
      - regex:
          expression: 'namespace="(?P<namespace>[^"]+)"'
          source: msg
      - labels:
          level:
          component:
          wf_task_queue_name:
          wf_task_queue_type:
          wf_namespace:
          lifecycle:
          workflow_id:
          workflow:
          task_queue:
          namespace:
