global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'payments-service'
    static_configs:
      - targets: ['payments-service:8080']

  - job_name: 'temporal'
    static_configs:
      - targets: ['temporal:7233']

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql-db:3306']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-cache:6379']
